[[foreman-context]]
# ForemanContext
:toc: right
:toclevels: 5

ForemanContext is an implementation of the new `React Context` API.
Global metadata (such as version, pagination, user, taxonomies, theme, foreman's settings, etc...) can be shared over all react nodes
without any redux integration nor API request.

### How to apply it

`Foreman Context` comes with every react component by default, like redux's store.

### Reading values from the context

Like selectors, you can consume context values by custom hooks:

```js
// ....
import {
  useForemanSettings,
  useForemanVersion,
  useForemanOrganization,
  useForemanLocation,
  useForemanUser,
  useForemanDocUrl,
  useForemanPermissions,
} from '../../Root/Context/ForemanContext';

const { perPage } = useForemanSettings();
const foremanVersion = useForemanVersion();
const { id: locationId, title: locationTitle } = useForemanLocation();
const { id: orgId, title: orgTitle } = useForemanOrganization();
const { id, login, firstname, lastname, admin } = useForemanUser();
const permissions = useForemanPermissions();
```

## How to add a value to the core context

Keys and values are set in the `core_app_metadata` method of `/application_helper.rb`.
The `app_metadata` object is passed down and becomes ForemanContext.

If you add a new value to `core_app_metadata`, it will also be useful to add a new custom hook in `webpack/assets/javascripts/react_app/Root/Context/ForemanContext.js`
so that the value can be easily consumed on the front end.
For example, Adding a new hook:
```js
// Context/ForemanContext.js

export const useForemanFeature = () => useForemanContext().feature;
```

## Adding a value to the context from a plugin

To add a value to the context from a plugin, the plugin must register the data like so:

```ruby
Foreman::Plugin.register :plugin_name do
  ...
  ::Foreman::Plugin.app_metadata_registry.register(:plugin_name, {
    context_key: 'context value',
  })
end
```

The value will then be in ForemanContext under the `:plugin_name` namespace:

```js
import { useForemanContext } from 'foremanReact/Root/Context/ForemanContext';
...
useForemanContext().metadata?.plugin_name?.context_key
```

